[package]
name = "ursa"
version = "0.1.0-dev-2"
authors = ["Michael Lodder <redmike7@gmail.com>"]
description = "This is the shared crypto library for Hyperledger components."
license = "Apache-2.0"
readme =  "../README.md"
repository = "https://github.com/hyperledger/ursa"
documentation = "https://docs.rs/ursa"
homepage = "https://crates.io/crates/ursa"

[lib]
name = "ursa"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib", "cdylib"]

[[bin]]
name = "test_secp256k1"
path = "bin/test_secp256k1.rs"
required-features = ["benchmarksecp256k1"]

[[bin]]
name = "test_ed25519"
path = "bin/test_ed25519.rs"
required-features = ["benchmarked25519"]

[features]
default = ["bn_openssl", "pair_amcl", "serialization", "native", "ffi", "cl", "bls"]
portable = ["bn_rust", "pair_amcl", "serialization", "rust-crypto-wasm", "rustlibsecp256k1", "cl", "bls"]
native = ["secp256k1", "libsodium-ffi"]
bn_openssl = ["openssl", "int_traits"]
bn_rust = ["num-bigint", "glass_pumpkin", "int_traits", "num-integer", "num-traits"]
pair_amcl = ["amcl"]
serialization = ["serde", "serde_json", "serde_derive"]
wasm = ["wasm-bindgen", "console_error_panic_hook", "portable"]
ffi = []
cl = []
bls = []
benchmarksecp256k1 = ["secp256k1", "openssl"]
benchmarked25519 = ["libsodium-ffi"]

[dependencies]
amcl = { version = "0.2",  optional = true, default-features = false, features = ["bn254", "secp256k1"]}
int_traits = { version = "0.1.1", optional = true }
arrayref = "0.3.5"
log = "0.4.1"
# TODO: Find out if the wasm-bindgen feature can be made dependent on our own wasm feature
rand = { version = "0.6", features = ["wasm-bindgen"] }
rand_chacha = "0.1"
sha2 = "0.7.1"
sha3 = "0.7.3"
time = "0.1.36"
env_logger = "0.5.10"
blake2b_simd = "0.3.1"
zeroize = "0.5"
openssl = { version = "0.10", optional = true }
serde = { version = "1.0",  optional = true}
serde_json = { version = "1.0",  optional = true}
serde_derive = { version = "1.0",  optional = true}
lazy_static = "1.0"
wasm-bindgen = { version = "0.2", optional = true, features = ["serde-serialize"] }
console_error_panic_hook = { version = "0.1.5", optional = true }
secp256k1 = { version = "0.12.0", optional = true, features = ["rand", "serde"]}
libsodium-ffi = { version = "0.1.12", optional = true }
rust-crypto-wasm = { version = "0.3", optional = true }
rustlibsecp256k1 = { version = "0.1.0", path = "rustlibsecp256k1", optional = true }
num-bigint = { version = "0.2", features = ["rand"], optional = true }
glass_pumpkin = { version = "0.3", optional = true }
num-integer = { version = "0.1", optional = true }
num-traits = { version = "0.2", optional = true }

[dev-dependencies]
secp256k1 = "0.12.0"
libsodium-ffi = "0.1.12"
rustlibsecp256k1 = { version = "0.1.0", path = "rustlibsecp256k1" }

[package.metadata.deb]
maintainer = "Hyperledger"
license-file = ["../LICENSE", "0"]
copyright = "2018, Hyperledger"
depends = "$auto"
extended-description = """\
Rust written reliable, secure, easy-to-use, and pluggable cryptographic implementations."""
section = "admin"
revision = "1"
priority = "optional"
assets = [
    ["target/release/libursa.a", "usr/lib", "644"],
    ["target/release/libursa.so", "usr/lib", "644"],
    ["include/ursa.h", "usr/include", "644"]
]

[package.metadata.rpm]
maintainer = "Hyperledger"
license-file = ["../LICENSE", "0"]
copyright = "2018, Hyperledger"
depends = "$auto"
extended-description = """\
Rust written reliable, secure, easy-to-use, and pluggable cryptographic implementations."""
section = "admin"
revision = "1"
priority = "optional"
